builtin_interfaces/Time stamp

bool sd_brake_warning1
bool sd_brake_warning2
bool sd_brake_warning3

bool est1_oos_front_brk
bool est2_oos_rear_brk
bool est6_sd_ebrake

bool sd_steer_warning1
bool sd_steer_warning2
bool sd_steer_warning3

bool est3_low_eng_speed

bool sd_system_warning
bool motec_warning

bool sd_system_failure
bool est4_sd_comms_loss
bool est5_motec_comms_loss
bool adlink_hb_lost
bool rc_lost
